### ISSUE TITLE
Reflective boundaries

### ISSUE THREAD

**Issue by nicolasmerino41** [rafaqz/Cellular.jl#249]
Hey there, 

I noticed there's not a reflective `BoundaryCondition` so I'm implementing one, but I cannot get through this issue:
`ERROR: MethodError: no method matching _update_padval(::Reflect, ::Float64)`

I've tried to add a method for update_padval(::Reflect, ) but still does not work. Here's my whole code. Once I'm done, I'll do a PR if you'd like to implement it, in the meantime I'd appreciate some insights on it.

```
struct Reflect <: BoundaryCondition end

@inline function _inbounds(::Reflect, size::Number, i::Number)
    if i < oneunit(i)
        return 2 - i, true
    elseif i > size
        return 2*size - i, true
    else
        return i, true

function _updateboundary!(g::DG.GridData{S,R}, ::Reflect) where {S<:Tuple{Y,X},R} where {Y,X}
    src = parent(source(g))
    #  Mirror the adjacent values
    # Left boundary
    @inbounds for i in 1:R
        src[:, i] = src[:, R + 1 - i]
    end
    # Right boundary
    @inbounds for i in 1:R
        src[:, end - i + 1] = src[:, end - R - i]
    end
    # Top boundary
    @inbounds for i in 1:R
        src[i, :] = src[R + 1 - i, :]
    end
    # Bottom boundary
    @inbounds for i in 1:R
        src[end - i + 1, :] = src[end - R - i, :]
    end
end

function _update_padval(::Reflect, ::Any)
    # No operation needed for a reflective, right?
    Reflect()
end
```

Cheers,
Nico

**Comment by rafaqz** [comment]
Awesome! Have thought about that too.


You might need to put `DynamicGrids._update_padval` ? Otherwise that may be adding a new function in local scope. (Not sure where you have this code)

Also `end` is missing from, `_inbounds` but maybe a typo.

Also feel free to make an in progress PR, it can be easier to discuss code inside that workflow

**Comment by nicolasmerino41** [comment]
Cool, I'll make the PR.
