### ISSUE TITLE
Define the neighborhood of SetNeighbors based on read data value 

### ISSUE THREAD

**Issue by remylegoff** [rafaqz/Cellular.jl#268]
Is it possible to create a SetNeighbors where the neighborhood is defined on the cell value of read data. Similar to : 
```julia
dispersion_rule =
    SetNeighbors{Tuple{:abundance,:dispersion_ability},Tuple{:abundance}}(neighborhood=VonNeuman{:dispersion_ability}) do data, hood, state, I 
        for pos in indices(hood, I)
                    migrate = state[:abundance]*state[:dispersion_rate]
                    add!(data[:abundance],migrate, pos...)
                    sub!(data[:abundance],migrate, I...)
                end
            end
    end
```

**Comment by rafaqz** [comment]
Does that code not work already?

If the dispersion rate is constant but spatial you can also put it in aux

**Comment by remylegoff** [comment]
I get the error : 
`ERROR: MethodError: no method matching radius(::Type{Moore{:dispersion_rate}})`

**Comment by rafaqz** [comment]
Oh I missed that bit with the type 

You want the neighbourhood length to change depending on the cell value?

(If so no, it would be horribly slow too. But you can hack if with an if block that just uses a different nighborhood based on the value. That will be fast)

**Comment by remylegoff** [comment]
Yes exactly. The cell value define the dispersal ability so the maximum distance that can be reach

**Comment by rafaqz** [comment]
Ok just use an if block to choose from the list of neighbourhoods.

Use the largest one as the rule neighbourhood so the bounds padding works.

**Comment by remylegoff** [comment]
Thanks a lot it's working great
